import { redis } from './redis/redis.js'
import { generateUser } from './utils.js'

(async () => {
  try {
    await redis.connect();
    const streamKey = 'PDS:demo:users';
    const batchSize = 100;    // Batch size for efficiency
    const totalUsers = 10000;

    console.log(`Erasing users...`);
    await redis.del(streamKey); 

    console.log(`Generating and inserting ${totalUsers} users...`);
    for (let i = 0; i < totalUsers; i += batchSize) {
      for (let j = 0; j < batchSize; j++) {
        redis.xAdd(streamKey, '*', JSON.stringify(generateUser()));
      }      
      console.log(`Inserted ${i + batchSize} users so far...`);
    }

    console.log(`Done inserting users...${await redis.xLen(streamKey)}`);

    await redis.quit();
  } catch (error) {
    console.error('Error:', error);
    await redis.quit();
  }
})();
/*
   Code template generated by copilot. 
*/